### ISSUE TITLE
v3.6 Proto Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Bus_Pirate#1]
(1) I think the Standoff drill hits should be part of a device and have a symbol in the SCH. We should use a standoff device with a symbol and a package from the eagle libraries. If we use a standardized device from the eagle library we can insure that the proper keepout and restrict elements are present, tested, and consistent.

(2) In the SCH the symbol for the cable connector uses a GND flag instead of a GND symbol on the GND net.

(3) USB connector currently has the wrong prefix in the Name field

(4) Level shifting IC currently has the wrong prefix in the Name field

(5) USB needs Tnames and Tvalues elements in the SCH

(6) 3.3V and 5V output traces from the vregs both have 20mil vias that are not masked on top or bottom. For testing purposes I only need the bottoms of the vias unmasked. Unless there is reasoning, I think the tops of these vias should be masked.

(7) VCC trace has two 20mil vias  that are not masked on top and bottom. I only need one of these vias unmasked on the bottom for testing (either one works for me), and unless there is reasoning, I think the tops of these vias should be masked.

(8) There are two GND vias that are unmasked on the top and the bottom. One is above the 1x5 header and one is to the left of the 2X5 connector. I think that both of these need mask on top and bottom unless there is a reason.

(9) R1, R5, R8 and all of the resistor arrays need some sort of silk in the package.

(10) Logic shifting IC needs a tPlace polarity marker that is outside of the package.

**Comment by BrentWilkins** [comment]
(1) This isn't our design.  It's using the 'DP6037' standard PCB footprint.
(2) Changed to our standard.
(3) Using an industry standard name (https://en.wikipedia.org/wiki/Reference_designator) to not confuse it with a jumper (JP).  Not alright?
(4) Changed for similar reason as (3).
(5) FIxed on our library
(6) That is caused by our standard DRC by the limit option under masks.  Should I change the DRC? I unmasked one of the vias on the 5V bus for you on the bottom only.  Interesting that none of us have used larger vias for more current capacity and uncovered this before(?)
(7) See response to (6)
(8) See response to (6)
(9) Added a rectangle that doesn't overlap tStop
(10) Moved out

**Comment by ericorosel** [comment]
Sorry it's been so long on this, I unsubscribe to repos so I never receive any notifications from activity on them.

(1) if the design is using a standard footprint 'DP6037' I think there needs to be a symbol for the footprint within schematic, or the standoffs need a symbol. 

(2) Thanks

(3) We've (QC) been using the engineering 'eagle rules' wiki for reference on prefixes. I agree with you that JP is not the appropriate prefix per the industry standard, but according the the Engineering Wiki, it is what we use for connectors. Maybe there is en explanation from someone in engineering as to why we have a different set of prefixes than the industry standard. 

(4) Thanks

(5) Thanks

(6) I see what you are talking about. I'm not entirely sure why we have the limit set to 20 mil. My only thought being that perhaps the drill is large enough that the mask would cover the metal on the top and the bottom of the via, but there would still be a hole that is not really masked closed? Or maybe it's something specific to GP? Having the vias unmasked on the top isn't the end of the world, but I would generally like to stay away from exposing metal unnecessarily, especially when it's metal on PWR or GND lines. Honestly, I think we could order protos with the tStop present, but I would like to get an explanation from engineering about why the 'limit' in the DRC is set to 20 mil.

(7) and (8) same as '(6)'

(9) thanks

(10) thanks

**Comment by BrentWilkins** [comment]
(1) I copied the one from their library and increased the width of the dimension to meet our 8mil spec.
(3) The DFM group is aware of this.  We can change it later if we decide not to improve our rules. It shouldn't delay this project.
(6) I increased it to 30mil for this board and manually added bStop for VCC, 5V, SW3V3, & SW5V0.

**Comment by ericorosel** [comment]
Pete informed me that the DFM group is looking into the prefixes that we use. Thanks for making that happen.

thanks for the fixes
